[build]
jobs = 1

[profile.dev]
debug = 1
codegen-units = 16
opt-level = "z"

[profile.release]
lto = true
opt-level = 3
strip = true
panic = "abort"
codegen-units = 1
rustflags = ["-Ctarget-cpu=native"]

[profile.release.package."*"]
opt-level = 3

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
